networks:
  traefik-tls:
    external: true

services:
  traefik:
   image: traefik:3.2.0
   healthcheck:
     test: 
       - CMD
       - traefik
       - healthcheck
     interval: 10s
     timeout: 5s
     retries: 3
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./traefik.yaml:/etc/traefik/traefik.yaml
     - ./certs/:/certs/
     - /var/run/docker.sock:/var/run/docker.sock
     #- ./config/traefik:/config:ro
   networks:
      - traefik-tls