services:
  
  traefik:
   image: traefik:2.11.2
   healthcheck:
     test: 
       - CMD
       - traefik
       - healthcheck
     interval: 10s
     timeout: 5s
     retries: 3
   ports:
     - 80:80
     - 443:443
   volumes:
     - ./traefik.yaml:/etc/traefik/traefik.yaml
     - ./certs/:/certs/
     - /var/run/docker.sock:/var/run/docker.sock
   networks:
      - traefiknet

networks:
  traefiknet:
    driver: bridge
